# Generated by Django 3.0.6 on 2020-05-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200524_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
    ]
