# Generated by Django 3.0.6 on 2020-05-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200524_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
