# Generated by Django 3.0.6 on 2020-05-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='display_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
