# Generated by Django 3.0.6 on 2020-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_vehicle_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.BinaryField(blank=True),
        ),
    ]
