# Generated by Django 3.0.6 on 2020-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
